- hosts: localhost
  connection: local

  name: PERFORM CONFIGURATION NFS EXPORTS FROM WESTERN DIGITAL EXTERNAL DISK
  gather_facts: no
  become: yes

  vars:
  # Explicitly telling Ansible to use Python3, because of the bug below:
  #     # https://github.com/ansible/ansible/issues/54855
  - ansible_python_interpreter: /usr/bin/python3

  tasks:

  - name: Create the mount point for both volumes
    file:
      path: '{{ item }}'
      state: directory
      owner: root
      group: root
    loop:
      - /mnt/sg3/
      - /mnt/wd_xfs1/
    tags:
    - nfs

  - name: Mount the filesystem for media/backups
    mount:
      path: /mnt/sg3
      src: LABEL=WD_SG3
      fstype: ext4
      state: mounted
      backup: yes
    tags:
    - nfs

  - name: Mount the filesystem for laptop image backups
    mount:
      path: /mnt/wd_xfs1
      src: LABEL=WD_XFS1
      fstype: xfs
      state: mounted
      backup: yes
    tags:
    - nfs

  - name: Open the appropriate firewall ports
    firewalld:
      zone: FedoraServer
      service: '{{ item }}'
      permanent: yes
      immediate: yes
      state: enabled
    loop:
      - nfs
      - nfs3
    tags:
    - nfs



